config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_uniqueness_of :movie_id, scope: [:list_id]
  validates :comment, length: { minimum: 6}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
     if @bookmark.save
      redirect_to list_path(@list)
     else
      render :new, status: :unprocessable_entity
     end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end

  end

  private


  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1> List </h1>
  <ul>
   <% @lists.each do |list| %>
     <li><%= link_to list.name, list_path(list) %></li>
     <% if list.photo.attached? %>
     <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
     <% end %>
    <% end%>
    <%= link_to "Add new list", new_list_path, class: "btn btn-primary mt-3"%>

  </ul>

app/views/lists/new.html.erb
<h1> Add new list </h1>
<%= simple_form_for(@list) do |f|%>
  <div class="form-input">
    <%= f.input :name %>
  </div>
  <div>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary mt_3"%>
  </div>
<% end%>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
<div class="card-category"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, width: 500 %>')"
<h1> <%= @list.name.capitalize %> </h1>
<% end %>


</div>

<% @bookmarks.each do |bookmark| %>
  <%= bookmark.movie.title %>
  <%=image_tag(bookmark.movie.poster_url)%>
  <%= bookmark.movie.overview%>
  <%= bookmark.movie.rating%>
  <%= bookmark.comment %>
<%= link_to "Delete bookmark", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
<% end %>

<br>
<%= link_to "Back to lists", root_path %>
<br>
<%= link_to "Add new bookmark", new_list_bookmark_path(@list) %>
<br>